### ISSUE TITLE
Issues with Prisma

### ISSUE THREAD

**Issue by peterschussheim** [peterschussheim/gamma#42]
# Problems with `prisma`

## Overview

I'd like this issue to serve as a 'mini' issue-tracker related to unresolved issues in `prisma` repo and/or workflows/features currently missing from `prisma`.

This is absolutely not a rant or a place to bash the Prisma team; quite the contrary.  They are a creative, hard working team and I am thankful for the work they have provided developers with.

The goal of this issue is to help others and myself **evaluate `prisma` as a legitimate tool for real world, production systems.**

## Outline of workflows/features currently missing in `prisma`

The features below are most important to me:

- [ ] Proper support for migrations
- [ ] Workflows for integrating with existing CI providers
- [ ] Robust integrations with service providers
- [ ] Heroku integration (currently broken)
- [ ] Support for GraphQL `unions` and `interfaces`
- [ ] Proper 'seeding' workflows
- [ ] Public roadmap
- [ ] Mediocre documentation (improving, but still not what it needs to be)
- [ ] lowering memory requirements for `prisma` services

## Non-technical concerns

- [ ] prisma slack channel is a ghost town
- [ ] many abstract terms and concepts specific to `prisma` change, just as you get something operational.  This has the potential for technical bugs in addition to excess cognition load.  Additionally, the docs have inconsistencies due to this.

## Related issues

- [ ] [Provide examples that leverage deployment stages](https://github.com/prisma/prisma/issues/2732)
- [ ] ["Clone service" feature](https://github.com/prisma/prisma/issues/2894)
- [ ] [Database migrations](https://github.com/prisma/prisma/issues/1263)
- [ ] [Interface types](https://github.com/prisma/prisma/issues/83)
- [ ] [Support union types](https://github.com/prisma/prisma/issues/165)
- [ ] [Public roadmap](https://github.com/prisma/prisma/issues/2142)
- [ ] [Add relation trigger for subscriptions](https://github.com/prisma/prisma/issues/146)
- [ ] [broken heroku integration](https://github.com/prisma/prisma-cloud-feedback/issues/191)
