### ISSUE TITLE
Convert 'web' source to TS

### ISSUE THREAD

**Issue by peterschussheim** [peterschussheim/gamma#81]
## Reference

https://github.com/jaredpalmer/razzle/blob/master/examples/with-typescript/README.md

## TODO

- [x] convert `.js` to `.ts` || `.tsx` where appropriate
- [x] swap `babel-loader` for `ts-loader` in webpack config
- [x] verify `gamma-config` can resolve `.ts` and `.tsx`
- [x] update `jest` to support TS files via adding `ts-jest` and `@types/jest` to our dev dependencies
- [x] update `jest` key in `package.json` with [appropriate settings](https://github.com/jaredpalmer/razzle/blob/master/examples/with-typescript/README.md#idea-behind-the-example)
